== Краткое руководство как читать яңа имлә

Если вы знакомы с https://ru.wikipedia.org/wiki/%D0%90%D1%80%D0%B0%D0%B1%D1%81%D0%BA%D0%BE%D0%B5_%D0%BF%D0%B8%D1%81%D1%8C%D0%BC%D0%BE[арабским письмом],
то большинство букв будут вам знакомы. Обратите внимание на гласные и на использование `ە` и `ھ`.

=== Соответствия букв

Таблица соответствия современного алфавита и яңа имлә

|===
| А | Ә | Б | В | Г | Ғ | Д | Е | Ё | Ж | Җ

| ئا ا | ئە، ە | ب | و، ۋ | گ | ﻉ | د | ئ ىُ | يۇ | ژ | ج
|===

|===
| З | И | Й | К | Қ | Л | М | Н | Ң | О, Ө | П

|  ز  |  ئي  |  ي   | ک | ﻕ | ل | ل | ن | ڭ |  ۇ ئۇ |  پ
|===

|===
| Р | С | Т | У, Ү | Ф | Х | Һ | Ц | Ч | Ш | Щ

| ر | س | ت | ئو  و | ف | ح | ھ  | _ | چ | ش  | _
|===

|===
| Ъ | Ы | Ь | Э | Ю | Я | |

| | ئ | | ﺋ | يو | يا يە | | ࢭ
|===

=== "Твердость" и "мягкость" слов

Обратите внимание, У/Ү и О/Ө обозначаются одной буквой. Чтобы понять, что произносить надо смотреть на твердость и мягкость слова.
На мягкость указывают буквы `ە`,`گ`,`ک`, на твердость `ا`,`ﻕ`,`ﻉ`.

.Например
* слово `قۇرت` (корт) твердое, об этом говорит наличие `ﻕ`.
* слово `كولمەك` (күлмәк) мягкое, об этом говорит наличие `ک`.

Если нет букв, по которым можно судить о твердости, то слова, по умолчанию, мягкие.
Если слово твердое, то перед ним ставится знак `ࢭ` (https://www.compart.com/en/unicode/U+08AD[малый алиф]).
Например `ࢭتۇز` (тоз), `تۇز` (төз).

=== "Выбрасывание" "е" и "ы" из середины слова

Буквы `ы` и `е` могут быть опущены, если стоят между согласными.
Обратите внимание на слова `قز` (кыз) и `کشىُ` (кеше).

Если знать татарский язык, то можно понять из контекста:  қзл - қызыл, кше - кеше, тимр - тимер, чүкч - чүкеч.

=== Буква `ئ` в начале слова

Если слово начинается на гласную, то перед ним ставится `ئ`.
Например `ئئتا` (ата), `ئەني` (әни), `ئش` (эш).
