== Как учить яңа имлә
:path-to-pages: https://github.com/dehasi/yana-imla/blob/main/
:darslege: {path-to-pages}tatar-tle-darslege/tatar-tle-darslege.adoc
:kitap: https://www.rulit.me/author/kurbangaliev-muhitdin-hafizitdinovich/rus-maktablare-ochn-tatar-tle-darslege-rus-m-download-258342.html

Татарский записанный в яңа имлә - это все тот же язык, только слова записаны другим алфавитом - арабской(персидской) графикой.
Чтобы научиться читать надо выучить арабскую графику. Для этого подойдет любой букварь или учебник татарского того времени.

Например, *Мухитдин Курбангалеев* и *Ходжа Бадиги* написали {kitap}[учебник татарского в арабской графике].

Чтобы выучить алфавит и научиться читать достаточно первых 13ти уроков.
Почти каждый урок дается несколько букв и слова с этими буквами.
Потом небольшой текст и упражнения на грамматику.

Арабские буквы пишутся по-разному в зависимо ти от того стоят они в начале середине или в конце слова.
В первых уроках используется шрифт, где все буквы одинаковы, что облегчает чтение.
В конце учебника есть словарь к каждому уроку.
В общем, {kitap}[скачайте] учебник и все увидите сами (первый урок на странице 7).

Но учебник написан как пособие для учителей и там ничего не объясняется, а для обозначения некоторых звуков используют странные буквы.
Поэтому я написал {darslege}[комментарии] к нескольким урокам и добавил перевод слов из словаря современный на татарский.

Вам может еще пригодиться русско-татарский https://www.rulit.me/author/kurbangaliev-muhitdin-hafizitdinovich/tatarsko-russkij-slovar-1927-god-arabica-tatarca-ursca-syzlek-download-247677.html[словарь] яңа имлә.
